server:
  context-path: /service-security
  port: 5090
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
     url: jdbc:oracle:thin:@localhost:1521:xe
     username: REG_HOTEL
     password: NUEVOF
     driver-class-name: oracle.jdbc.OracleDriver
  jpa:
     hibernate: 
        naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
     database-platform: org.hibernate.dialect.Oracle10gDialect   
     show-sql: true
     properties:
       hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
       hibernate.ejb.interceptor: pe.com.socialdata.hotel.repository.ApiEntityInterceptorImpl
